//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int airportId { get; set; }
        public string airportName { get; set; }
        public string IATA { get; set; }
        public string country { get; set; }
    }
}
